# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Python

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
           python -m pip install --upgrade pip
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: tx816
      run: |
           python minidexed2reaper.py
           python performancelint.py tx816
    - name: dx7IId
      run: |
           git clone https://github.com/Perlence/rpp rppgit
           python create-rpp.py
    - uses: actions/upload-artifact@v4
      with:
        name: tx816_and_dx7IId
        path: |
          tx816.rpp
          dx7IId_modified.rpp
          tx816
          dx7IId

    - name: Upload to GitHub Releases (only when building from main branch)
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
           set -ex
           wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
           bash ./upload.sh ./tx816.zip ./dx7IId.zip

